### ISSUE TITLE
Help with Cordova 7

### ISSUE THREAD

**Issue by jybaro** [phearme/cordova-ContentProviderPlugin#4]
Hi, please help, the installation doesn't work in Cordova 7.

**Comment by jybaro** [comment]
#5 fixed with the creation of package.json file

**Comment by phearme** [comment]
Hi. I haven't tried it with Cordova 7. Does your commit (the one with package.json file) solve the issue?

**Comment by jybaro** [comment]
Hi, yes I can confirm. I was working with this plugin in Cordova 5 without issues, then I upgrade to Cordova 7 and there was a ENOENT error with package.json. After aggregate this file, the problem was gone.

**Comment by phearme** [comment]
Cool. Will merge it later today. Thanks.

**Comment by phearme** [comment]
merged.
