### ISSUE TITLE
Not able to install on cordova 7

### ISSUE THREAD

**Issue by forumact** [phearme/cordova-ContentProviderPlugin#6]
Hi,

I am trying to install this plugin on cordova 7 and am getting below error. Please suggest me to resolve this issue.
![cp](https://user-images.githubusercontent.com/36502276/36252609-35069e82-126b-11e8-85ce-5c23e26c0664.PNG)

**Comment by phearme** [comment]
as the error message states, it is very likely a connection problem, or a problem with you cordova install. the error msg also states `Error not found git`, maybe your cordova install requires that you have git installed and in your path.

**Comment by forumact** [comment]
Thanks for your quick reply. now its working. However after successful installed  am getting "Unknown error" while querying data from content provider.

**Comment by forumact** [comment]
Hi, 

Find below details for content provider information.  I need to fetch data from "tbl_test_sso" table please provide any suggestion to access tbl_test_sso data.

a.	Android content provider URL:- content://com.xxx.provider.TESTSSO/data
b.	Database name: TESTSSODB
c.	Table tbl_test_sso_appid storing child app package id, which child app invoke the parent app
d.	Table tbl_test_sso storing parent app’s login details in AES encrypted string format.

**Comment by phearme** [comment]
Hi.
The only thing I can recommend is to try first with an OS content provider, like sms or contacts as in the example, and see that your setup works fine. Then if you are able to get a content provider to work ok, or you have already done that, proceed to test your content provider. Did you check that your app has the right permissions to access `com.xxx.provider.TESTSSO`? Is the content provider published correctly and has granted access for other apps to query it?

**Comment by phearme** [comment]
also, I have noticed you have not specified any fields in `projection`, you should specify at least one field, for example:
```
projection: ["address", "date", "body"],
```

**Comment by forumact** [comment]
Thanks,
 I have tried below code on my device ready function, while opening my application says "Unfortunately, xxxx has stopped". i have added permission on androidmanifest.xml file too..

**permission tag: <uses-permission android:name="android.permission.READ_SMS" />**


				window.plugins.contentproviderplugin.query({
					    contentUri: "content://sms/inbox",
						projection: ["address", "date", "body"],
						selection: null,
						selectionArgs: null,						
					}, function (data) {
						app.dialog.alert(JSON.stringify(data));
					}, function (err) {
						app.dialog.alert(err);
				});	

Device : Motog3
Cordova version : 7

**Comment by forumact** [comment]
I am new to mobile development and i have no idea about logcat.

**Comment by forumact** [comment]
Can you share sample APK with content provider its helps me lot to fixing my issues.

**Comment by forumact** [comment]
Hi any updates for this issue?

**Comment by phearme** [comment]
Hi. I'm afraid I cannot help you if you don't provide the exact error your are having. Please use adb or logcat or anything to provide the error.
